=== VijayEluri/com.idega.xformsmanager/resources/templates/select-data-src.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.idega.is/select-data-src/"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.idega.is/select-data-src/" elementFormDefault="qualified">

	<xs:element name="choiceListData" type="choiceListDataType"></xs:element>

	<xs:complexType name="choiceListDataType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="localizedEntries"
				type="localizedEntriesType" minOccurs="0" maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="localizedEntriesType">
		<xs:sequence>
			<xs:element name="item" type="itemType" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="lang" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="itemType">
		<xs:sequence>
			<xs:element name="itemLabel" type="xs:string"></xs:element>
			<xs:element name="itemValue" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== VijayEluri/com.idega.xformsmanager/resources/templates/select-data-src.xml
<?xml version="1.0" encoding="UTF-8"?>
<choiceListData
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.idega.is/select-data-src/ select-data-src.xsd">

	<localizedEntries lang="en"> 
	  <item>
        <itemLabel>Country</itemLabel>
        <itemValue></itemValue>
      </item>
	  <item>
        <itemLabel>Lithuania</itemLabel>
        <itemValue>lt</itemValue>
      </item>
	  <item>
        <itemLabel>Iceland</itemLabel>
        <itemValue>is</itemValue>
      </item>
      <item>
        <itemLabel>Legoland</itemLabel>
        <itemValue>ll</itemValue>
      </item>
	</localizedEntries>
	<localizedEntries lang="is">
	  <item>
        <itemLabel>eg tala islensku</itemLabel>
        <itemValue>lt</itemValue>
      </item>
	  <item>
        <itemLabel>eg tala ekki islensku</itemLabel>
        <itemValue>ekki</itemValue>
      </item>
	</localizedEntries>
</choiceListData>
